exclude_patterns:
  - "/vendor/*"
  - "/public/css/*"
  - "/public/js/*"
  - "/includes/class-property-carousel-i18n.php"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "WordPress"
      ignore_warnings: true
      encoding: utf-8
