exclude_paths:
  - "/vendor/*"
  - "/public/css/*"
  - "/public/js/*"
  - "/includes/class-property-carousel-i18n.php"

engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "WordPress"
      ignore_warnings: true
      encoding: utf-8

ratings:
  paths:
    - "**.php"